ALTER PROCEDURE PA_ANADIR_STOCK
(
	@ID_ARTICULO INT,
	@CANTIDAD	INT,

	@MENSAJE VARCHAR(2000) OUTPUT,
	@RETCODE INT OUTPUT
)
AS
BEGIN TRY
	
	IF ISNULL(@ID_ARTICULO,0) = 0
	BEGIN
		SET @MENSAJE = 'Id artículo no informado'
		SET @RETCODE = 1
		RETURN
	END

	IF ISNULL(@CANTIDAD,0) <= 0
	BEGIN
		SET @MENSAJE = 'La cantidad no puede ser 0 o inferior'
		SET @RETCODE = 1
		RETURN
	END

	INSERT INTO STOCKS 
	(
		ID_ARTICULO,
		CANTIDAD
	) 
	VALUES
	(
		@ID_ARTICULO,
		@CANTIDAD
	)

	

	UPDATE STOCKS SET LOTE = LEFT(REPLACE(NEWID(),'-',''),10) WHERE ID_STOCK = SCOPE_IDENTITY()

	SET @RETCODE = 0
	RETURN
END TRY
BEGIN CATCH
	SET @RETCODE = -1
END CATCH