ALTER PROCEDURE PA_ANADIR_ARTICULO_A_PEDIDO
(
	@ID_PEDIDO INT,
	@ID_ARTICULO INT,
	@CANTIDAD_ARTIULO INT,

	@MENSAJE VARCHAR(2000) OUTPUT,
	@RETCODE INT OUTPUT
)
AS
BEGIN TRY
	
	DECLARE @ID_STOCK INT = 0
	DECLARE @CANTIDAD_BUSCADA INT = 0
	DECLARE @CANTIDAD_ENCONTRADA INT = 0
	
	IF ISNULL(@ID_ARTICULO,0) = 0
	BEGIN
		SET @MENSAJE = 'Id artículo no informado'
		SET @RETCODE = 1
		RETURN
	END

	IF ISNULL(@ID_PEDIDO,0) = 0
	BEGIN
		SET @MENSAJE = 'Id pedido no informado'
		SET @RETCODE = 1
		RETURN
	END

	IF ISNULL(@CANTIDAD_ARTIULO,0) = 0
	BEGIN
		SET @MENSAJE = 'Cantidad no informada'
		SET @RETCODE = 1
		RETURN
	END

	IF NOT EXISTS (SELECT * FROM PEDIDOS WHERE ID_PEDIDO = @ID_PEDIDO)
	BEGIN
		SET @MENSAJE = 'Pedido no encontrado'
		SET @RETCODE = 1
		RETURN
	END

	IF  EXISTS (SELECT * FROM PEDIDOS_STOCK WHERE ID_PEDIDO = @ID_PEDIDO)
	BEGIN
		SET @MENSAJE = 'Pedido actualmente registrado'
		SET @RETCODE = 1
		RETURN
	END

	
	WHILE ISNULL(@CANTIDAD_ARTIULO,0) > 0
	BEGIN
			SELECT	TOP 1 
					@ID_STOCK = ID_STOCK,
					@CANTIDAD_BUSCADA = CANTIDAD
			
			FROM	STOCKS
			WHERE	ID_ARTICULO = @ID_ARTICULO
			AND		CANTIDAD > 0
			ORDER BY
					CANTIDAD ASC

			WHILE ISNULL(@CANTIDAD_BUSCADA,0) <> 0 
			BEGIN
				
				SET @CANTIDAD_ENCONTRADA = @CANTIDAD_BUSCADA
				SET @CANTIDAD_BUSCADA = 0


				SELECT	TOP 1 
						@ID_STOCK = ID_STOCK,
						@CANTIDAD_BUSCADA = CANTIDAD
		
				FROM	STOCKS
				WHERE	ID_ARTICULO = @ID_ARTICULO
				AND		CANTIDAD <= @CANTIDAD_ARTIULO
				AND		CANTIDAD > @CANTIDAD_ENCONTRADA
				ORDER BY
						CANTIDAD ASC 	

			END

			SELECT @CANTIDAD_ARTIULO, @CANTIDAD_ENCONTRADA, @ID_STOCK, @ID_PEDIDO


			IF @CANTIDAD_ARTIULO - @CANTIDAD_ENCONTRADA < 0
			BEGIN

				INSERT INTO PEDIDOS_STOCK
				(
					ID_PEDIDO,
					ID_STOCK,
					CANTIDAD
				)
				VALUES
				(
					@ID_PEDIDO,
					@ID_STOCK,
					@CANTIDAD_ARTIULO
				)

				UPDATE	STOCKS
				SET		CANTIDAD = CANTIDAD - @CANTIDAD_ARTIULO
				WHERE	ID_STOCK = @ID_STOCK

				SET @CANTIDAD_ARTIULO = 0
				
			END
			ELSE
			BEGIN

				INSERT INTO PEDIDOS_STOCK
				(
					ID_PEDIDO,
					ID_STOCK,
					CANTIDAD
				)
				VALUES
				(
					@ID_PEDIDO,
					@ID_STOCK,
					@CANTIDAD_ENCONTRADA
				)

				UPDATE	STOCKS
				SET		CANTIDAD = CANTIDAD - @CANTIDAD_ENCONTRADA
				WHERE	ID_STOCK = @ID_STOCK
								
				SET @CANTIDAD_ARTIULO = @CANTIDAD_ARTIULO - @CANTIDAD_ENCONTRADA

			END

			

	END


	

	IF ISNULL(@ID_STOCK,0) = 0
	BEGIN
		SET @MENSAJE = 'Stock no encontrado'
		SET @RETCODE = 1
		RETURN
	END

	

	SET @RETCODE = 0
	RETURN
END TRY
BEGIN CATCH

	SET @MENSAJE = ERROR_MESSAGE()
	SET @RETCODE = -1
END CATCH