create PROCEDURE PA_ALTAUSUARIO
(
	@USUARIO VARCHAR(50),
	@PASSWORD VARCHAR(50),
	@EMAIL VARCHAR(100),

	@ID_USUARIO INT OUTPUT,
	@MENSAJE VARCHAR(2000) OUTPUT,
	@RETCODE INT OUTPUT
)
AS 
BEGIN TRY 

	IF ISNULL(@USUARIO,'') = ''
	BEGIN
		SET @MENSAJE = 'Falta dato Usuario'
		SET @RETCODE = 1
		RETURN
	END

	IF ISNULL(@PASSWORD,'') = ''
	BEGIN
		SET @MENSAJE = 'Falta dato Contraseña'
		SET @RETCODE = 1
		RETURN
	END

	IF ISNULL(@EMAIL,'') = ''
	BEGIN
		SET @MENSAJE = 'Falta dato email'
		SET @RETCODE = 1
		RETURN
	END

	IF NOT EXISTS (SELECT * FROM USUARIOS WHERE USUARIO = @USUARIO AND EMAIL = @EMAIL)
	BEGIN
		INSERT INTO USUARIOS(USUARIO,EMAIL,PASSWORD,ACTIVO,ID_PERFIL) VALUES(@USUARIO,@EMAIL,@PASSWORD,1,3);
		SET @RETCODE = 0
	END
	
END TRY

BEGIN CATCH
	SET @RETCODE = -1
END CATCH
