ALTER PROCEDURE PA_CREAR_PEDIDO
(
	@DIRECCION VARCHAR(300),
	@PISO	VARCHAR(20),
	@PUERTA	VARCHAR(20),
	@CODIGO_POSTAL	VARCHAR(20),
	@NOMBRE_CLIENTE	VARCHAR(20),

	@MENSAJE VARCHAR(2000) OUTPUT,
	@RETCODE INT OUTPUT
)
AS
BEGIN TRY
	
	DECLARE @ID_PEDIDO INT = 0
	DECLARE @COD_PEDIDO VARCHAR(20) = ''

	IF ISNULL(@DIRECCION,'') = ''
	BEGIN
		SET @MENSAJE = 'Dirección no informada'
		SET @RETCODE = 1
		RETURN
	END

	IF ISNULL(@PISO,'') = ''
	BEGIN
		SET @MENSAJE = 'Piso no informado'
		SET @RETCODE = 1
		RETURN
	END

	IF ISNULL(@PUERTA,'') = ''
	BEGIN
		SET @MENSAJE = 'Puerta no informada'
		SET @RETCODE = 1
		RETURN
	END

	IF ISNULL(@CODIGO_POSTAL,'') = ''
	BEGIN
		SET @MENSAJE = 'Código postal no informado'
		SET @RETCODE = 1
		RETURN
	END

	IF ISNULL(@NOMBRE_CLIENTE,'') = ''
	BEGIN
		SET @MENSAJE = 'Nombre del cliente no informado'
		SET @RETCODE = 1
		RETURN
	END

	INSERT INTO PEDIDOS 
	(
		DIRECCION,
		PISO,
		PUERTA,
		CODIGO_POSTAL,
		NOMBRE_CLIENTE
	) 
	VALUES
	(
		@DIRECCION,
		@PISO,
		@PUERTA,
		@CODIGO_POSTAL,
		@NOMBRE_CLIENTE
	)

	SET @ID_PEDIDO = SCOPE_IDENTITY()

	SET @COD_PEDIDO = LEFT(REPLACE(NEWID(),'-',''),20)

	UPDATE PEDIDOS SET COD_PEDIDO = @COD_PEDIDO WHERE ID_PEDIDO = @ID_PEDIDO

	SET @RETCODE = 0
	RETURN
END TRY
BEGIN CATCH

	SET @MENSAJE = ERROR_MESSAGE()
	SET @RETCODE = -1
END CATCH