create PROCEDURE PA_LOGIN
(
	@USUARIO VARCHAR(50),
	@PASSWORD VARCHAR(20),

	@ID_USUARIO INT OUTPUT,
	@MENSAJE VARCHAR(2000) OUTPUT,
	@RETCODE INT OUTPUT
)
AS 
BEGIN TRY 

	IF ISNULL(@USUARIO,'') = ''
	BEGIN
		SET @MENSAJE = 'Falta dato Usuario'
		SET @RETCODE = 1
		RETURN
	END

	IF ISNULL(@PASSWORD,'') = ''
	BEGIN
		SET @MENSAJE = 'Falta dato Contraseña'
		SET @RETCODE = 1
		RETURN
	END

	IF NOT EXISTS (SELECT * FROM USUARIOS WHERE USUARIO = @USUARIO AND PASSWORD = @PASSWORD)
	BEGIN
		SET @MENSAJE = 'No existe el usuario/contraseña'
		SET @RETCODE = 1
		RETURN
	END

	IF EXISTS (SELECT * FROM USUARIOS WHERE USUARIO = @USUARIO AND PASSWORD = @PASSWORD AND ACTIVO = 0)
	BEGIN
		SET @MENSAJE = 'usuario no activo'
		SET @RETCODE = 1
		RETURN
	END

	SELECT @ID_USUARIO = ID_USUARIO FROM USUARIOS WHERE USUARIO = @USUARIO

	SET @RETCODE = 0

END TRY

BEGIN CATCH
	SET @RETCODE = -1
END CATCH