USE [ALMACEN]
GO

/****** Object:  Table [dbo].[STOCKS]    Script Date: 02/05/2022 20:10:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STOCKS](
	[ID_STOCK] [int] IDENTITY(1,1) NOT NULL,
	[ID_ARTICULO] [int] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[LOTE] [varchar](10) NULL,
 CONSTRAINT [PK_STOCKS] PRIMARY KEY CLUSTERED 
(
	[ID_STOCK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STOCKS]  WITH CHECK ADD  CONSTRAINT [FK_STOCKS_ARTICULOS] FOREIGN KEY([ID_ARTICULO])
REFERENCES [dbo].[ARTICULOS] ([ID_ARTICULO])
GO

ALTER TABLE [dbo].[STOCKS] CHECK CONSTRAINT [FK_STOCKS_ARTICULOS]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FK' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'STOCKS', @level2type=N'CONSTRAINT',@level2name=N'FK_STOCKS_ARTICULOS'
GO


