USE [ALMACEN]
GO

/****** Object:  Table [dbo].[PEDIDOS]    Script Date: 02/05/2022 20:09:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PEDIDOS](
	[ID_PEDIDO] [int] IDENTITY(1,1) NOT NULL,
	[COD_PEDIDO] [varchar](20) NULL,
	[DIRECCION] [varchar](300) NOT NULL,
	[PISO] [varchar](20) NOT NULL,
	[PUERTA] [varchar](20) NOT NULL,
	[CODIGO_POSTAL] [varchar](20) NOT NULL,
	[NOMBRE_CLIENTE] [varchar](100) NOT NULL,
 CONSTRAINT [PK_PEDIDOS] PRIMARY KEY CLUSTERED 
(
	[ID_PEDIDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


