USE [ALMACEN]
GO

/****** Object:  Table [dbo].[PEDIDOS_STOCK]    Script Date: 02/05/2022 20:09:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PEDIDOS_STOCK](
	[ID_PEDIDO_STOCK] [int] IDENTITY(1,1) NOT NULL,
	[ID_PEDIDO] [int] NOT NULL,
	[ID_STOCK] [int] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
 CONSTRAINT [PK_PEDIDOS_STOCK] PRIMARY KEY CLUSTERED 
(
	[ID_PEDIDO_STOCK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PEDIDOS_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_PEDIDOS_STOCK_PEDIDO] FOREIGN KEY([ID_PEDIDO])
REFERENCES [dbo].[PEDIDOS] ([ID_PEDIDO])
GO

ALTER TABLE [dbo].[PEDIDOS_STOCK] CHECK CONSTRAINT [FK_PEDIDOS_STOCK_PEDIDO]
GO

ALTER TABLE [dbo].[PEDIDOS_STOCK]  WITH CHECK ADD  CONSTRAINT [FK_PEDIDOS_STOCK_STOCK] FOREIGN KEY([ID_STOCK])
REFERENCES [dbo].[STOCKS] ([ID_STOCK])
GO

ALTER TABLE [dbo].[PEDIDOS_STOCK] CHECK CONSTRAINT [FK_PEDIDOS_STOCK_STOCK]
GO


