CREATE VIEW V_STOCK_ARTICULOS
AS

	SELECT	
			A.ID_ARTICULO,
			A.NOMBRE,
			A.PESO,
			A.ALTO,
			A.ANCHO,
			S.CANTIDAD
	FROM	ARTICULOS A

			OUTER APPLY
			(
				SELECT	SUM(CANTIDAD) CANTIDAD
				FROM	STOCKS S1
				WHERE	S1.ID_ARTICULO = A.ID_ARTICULO
			) S